FROM liquibase/liquibase:4.30-alpine

ENTRYPOINT docker-entrypoint.sh \
      --changelogFile=changelog/changelog.yaml \
      --log-level=INFO \
      --show-banner=false \
      --url="$JDBC_URL" \
      --username="$USER" \
      --password="$PASSWORD" \
      update